/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectzui;

import static com.mycompany.projectzui.ConsoleUtils.exec;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.EventQueue;
import java.awt.Robot;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.Parent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import sun.applet.Main;
import sun.security.util.SecurityConstants.AWT;

/**
 *
 * @author Hp
 */
public class ZUI_app extends javax.swing.JFrame {
    
    private int mouseX, mouseY;
    JFileChooser chooseFile = new JFileChooser();

    //private PrintStream standardOut;
    /**
     * Creates new form ZUI_app
     *
     */
    public ZUI_app() {
        initComponents();
        
        chooseFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        PrintStream ps = new PrintStream(new CustomOutputStream(output));
       // System.setOut(ps);
        //System.setErr(ps);
        //  PrintStream standardOut = System.out;
        //  PrintStream standardErr = System.err;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        restoreSize = new javax.swing.JPanel();
        btnResize = new javax.swing.JButton();
        minimize = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        file = new javax.swing.JPanel();
        btnOpenFile = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        btnReport = new javax.swing.JButton();
        playPanel = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        repAllPannel = new javax.swing.JPanel();
        btnRepAll = new javax.swing.JButton();
        repeatPanel = new javax.swing.JPanel();
        btnRepLast = new javax.swing.JButton();
        contPanel = new javax.swing.JPanel();
        btnContinue = new javax.swing.JButton();
        stopPanel = new javax.swing.JPanel();
        btnStop = new javax.swing.JButton();
        createTCPanel = new javax.swing.JPanel();
        btnCreateTC = new javax.swing.JButton();
        createProjectPanel = new javax.swing.JPanel();
        btnCreateProject = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        headless = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        outPanel = new javax.swing.JPanel();
        jScrollout = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        dirPath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 750));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 40));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(51, 51, 51));
        close.setPreferredSize(new java.awt.Dimension(50, 40));

        btnClose.setBackground(new java.awt.Color(51, 51, 51));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-close-24.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 40));

        restoreSize.setBackground(new java.awt.Color(204, 204, 204));
        restoreSize.setPreferredSize(new java.awt.Dimension(50, 40));

        btnResize.setBackground(new java.awt.Color(51, 51, 51));
        btnResize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-maximize-24.png"))); // NOI18N
        btnResize.setBorder(null);
        btnResize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResizeMouseExited(evt);
            }
        });
        btnResize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout restoreSizeLayout = new javax.swing.GroupLayout(restoreSize);
        restoreSize.setLayout(restoreSizeLayout);
        restoreSizeLayout.setHorizontalGroup(
            restoreSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResize, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        restoreSizeLayout.setVerticalGroup(
            restoreSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResize, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(restoreSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, -1));

        minimize.setBackground(new java.awt.Color(204, 204, 204));
        minimize.setPreferredSize(new java.awt.Dimension(50, 40));

        btnMinimize.setBackground(new java.awt.Color(51, 51, 51));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-subtract-24.png"))); // NOI18N
        btnMinimize.setBorder(null);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout minimizeLayout = new javax.swing.GroupLayout(minimize);
        minimize.setLayout(minimizeLayout);
        minimizeLayout.setHorizontalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        minimizeLayout.setVerticalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, -1));

        jPanel1.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new java.awt.BorderLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("ZUI");
        title.setPreferredSize(new java.awt.Dimension(900, 34));
        title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleMouseDragged(evt);
            }
        });
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleMousePressed(evt);
            }
        });
        jPanel8.add(title, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 60));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(900, 5));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setPreferredSize(new java.awt.Dimension(10, 55));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));
        jPanel12.setPreferredSize(new java.awt.Dimension(650, 55));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        file.setBackground(new java.awt.Color(153, 153, 153));
        file.setPreferredSize(new java.awt.Dimension(60, 55));

        btnOpenFile.setBackground(new java.awt.Color(153, 153, 153));
        btnOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-opened-folder-50.png"))); // NOI18N
        btnOpenFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOpenFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOpenFileMouseExited(evt);
            }
        });
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileLayout = new javax.swing.GroupLayout(file);
        file.setLayout(fileLayout);
        fileLayout.setHorizontalGroup(
            fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLayout.createSequentialGroup()
                .addComponent(btnOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        fileLayout.setVerticalGroup(
            fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(btnOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.add(file, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        reportPanel.setBackground(new java.awt.Color(153, 153, 153));
        reportPanel.setPreferredSize(new java.awt.Dimension(60, 55));

        btnReport.setBackground(new java.awt.Color(153, 153, 153));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-report-48.png"))); // NOI18N
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReport))
        );

        jPanel12.add(reportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 60, -1));

        playPanel.setBackground(new java.awt.Color(153, 153, 153));
        playPanel.setPreferredSize(new java.awt.Dimension(60, 55));

        btnPlay.setBackground(new java.awt.Color(153, 153, 153));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-play-30.png"))); // NOI18N
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlayMouseExited(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playPanelLayout = new javax.swing.GroupLayout(playPanel);
        playPanel.setLayout(playPanelLayout);
        playPanelLayout.setHorizontalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playPanelLayout.createSequentialGroup()
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        playPanelLayout.setVerticalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.add(playPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 60, -1));

        repAllPannel.setBackground(new java.awt.Color(153, 153, 153));
        repAllPannel.setPreferredSize(new java.awt.Dimension(60, 55));

        btnRepAll.setBackground(new java.awt.Color(153, 153, 153));
        btnRepAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-repeat-48.png"))); // NOI18N
        btnRepAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRepAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRepAllMouseExited(evt);
            }
        });
        btnRepAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout repAllPannelLayout = new javax.swing.GroupLayout(repAllPannel);
        repAllPannel.setLayout(repAllPannelLayout);
        repAllPannelLayout.setHorizontalGroup(
            repAllPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repAllPannelLayout.createSequentialGroup()
                .addComponent(btnRepAll, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        repAllPannelLayout.setVerticalGroup(
            repAllPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, repAllPannelLayout.createSequentialGroup()
                .addComponent(btnRepAll)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel12.add(repAllPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 60, -1));

        repeatPanel.setBackground(new java.awt.Color(153, 153, 153));
        repeatPanel.setPreferredSize(new java.awt.Dimension(60, 55));

        btnRepLast.setBackground(new java.awt.Color(153, 153, 153));
        btnRepLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-repeat-48_1.png"))); // NOI18N
        btnRepLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRepLastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRepLastMouseExited(evt);
            }
        });

        javax.swing.GroupLayout repeatPanelLayout = new javax.swing.GroupLayout(repeatPanel);
        repeatPanel.setLayout(repeatPanelLayout);
        repeatPanelLayout.setHorizontalGroup(
            repeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repeatPanelLayout.createSequentialGroup()
                .addComponent(btnRepLast, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        repeatPanelLayout.setVerticalGroup(
            repeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, repeatPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRepLast, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.add(repeatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 60, -1));

        contPanel.setBackground(new java.awt.Color(153, 153, 153));
        contPanel.setPreferredSize(new java.awt.Dimension(60, 55));

        btnContinue.setBackground(new java.awt.Color(153, 153, 153));
        btnContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-forward-button-48.png"))); // NOI18N
        btnContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContinueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContinueMouseExited(evt);
            }
        });
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contPanelLayout = new javax.swing.GroupLayout(contPanel);
        contPanel.setLayout(contPanelLayout);
        contPanelLayout.setHorizontalGroup(
            contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contPanelLayout.createSequentialGroup()
                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        contPanelLayout.setVerticalGroup(
            contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contPanelLayout.createSequentialGroup()
                .addComponent(btnContinue)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel12.add(contPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 60, -1));

        stopPanel.setBackground(new java.awt.Color(153, 153, 153));
        stopPanel.setPreferredSize(new java.awt.Dimension(60, 55));

        btnStop.setBackground(new java.awt.Color(153, 153, 153));
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-stop-48.png"))); // NOI18N
        btnStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStopMouseExited(evt);
            }
        });
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stopPanelLayout = new javax.swing.GroupLayout(stopPanel);
        stopPanel.setLayout(stopPanelLayout);
        stopPanelLayout.setHorizontalGroup(
            stopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopPanelLayout.createSequentialGroup()
                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        stopPanelLayout.setVerticalGroup(
            stopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopPanelLayout.createSequentialGroup()
                .addComponent(btnStop)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel12.add(stopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 60, -1));

        createTCPanel.setBackground(new java.awt.Color(153, 153, 153));
        createTCPanel.setPreferredSize(new java.awt.Dimension(60, 55));

        btnCreateTC.setBackground(new java.awt.Color(153, 153, 153));
        btnCreateTC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add-file-48.png"))); // NOI18N
        btnCreateTC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateTCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateTCMouseExited(evt);
            }
        });
        btnCreateTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createTCPanelLayout = new javax.swing.GroupLayout(createTCPanel);
        createTCPanel.setLayout(createTCPanelLayout);
        createTCPanelLayout.setHorizontalGroup(
            createTCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTCPanelLayout.createSequentialGroup()
                .addComponent(btnCreateTC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        createTCPanelLayout.setVerticalGroup(
            createTCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createTCPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCreateTC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.add(createTCPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        createProjectPanel.setBackground(new java.awt.Color(153, 153, 153));
        createProjectPanel.setPreferredSize(new java.awt.Dimension(60, 55));
        createProjectPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createProjectPanelMouseEntered(evt);
            }
        });

        btnCreateProject.setBackground(new java.awt.Color(153, 153, 153));
        btnCreateProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add-folder-48.png"))); // NOI18N
        btnCreateProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateProjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateProjectMouseExited(evt);
            }
        });
        btnCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createProjectPanelLayout = new javax.swing.GroupLayout(createProjectPanel);
        createProjectPanel.setLayout(createProjectPanelLayout);
        createProjectPanelLayout.setHorizontalGroup(
            createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createProjectPanelLayout.createSequentialGroup()
                .addComponent(btnCreateProject, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        createProjectPanelLayout.setVerticalGroup(
            createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createProjectPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCreateProject, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.add(createProjectPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel11.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 38));
        jPanel9.setLayout(new java.awt.BorderLayout());

        headless.setBackground(new java.awt.Color(153, 153, 153));
        headless.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headless.setText("Headless Mode");
        headless.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.add(headless, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(900, 10));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        outPanel.setBackground(new java.awt.Color(204, 204, 255));
        outPanel.setLayout(new java.awt.BorderLayout());

        output.setColumns(20);
        output.setRows(5);
        output.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Command Line Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        jScrollout.setViewportView(output);
        output.getAccessibleContext().setAccessibleParent(outPanel);

        outPanel.add(jScrollout, java.awt.BorderLayout.CENTER);
        outPanel.add(dirPath, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(outPanel, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Sure? You want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.dispose();
        } else if (response == JOptionPane.NO_OPTION) {
            
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        close.setBackground(Color.red);
        btnClose.setBackground(Color.red);

    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        close.setBackground(Color.getColor("#333333"));
        btnClose.setBackground(Color.getColor("#333333"));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnResizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResizeMouseEntered
        // TODO add your handling code here:
        restoreSize.setBackground(Color.DARK_GRAY);
        btnResize.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnResizeMouseEntered

    private void btnResizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResizeMouseExited
        // TODO add your handling code here:
        restoreSize.setBackground(Color.getColor("#333333"));
        btnResize.setBackground(Color.getColor("#333333"));
    }//GEN-LAST:event_btnResizeMouseExited

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        // TODO add your handling code here:
        minimize.setBackground(Color.DARK_GRAY);
        btnMinimize.setBackground(Color.DARK_GRAY);

    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        // TODO add your handling code here:
        minimize.setBackground(Color.getColor("#333333"));
        btnMinimize.setBackground(Color.getColor("#333333"));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        // TODO add your handling code here:
//        if (btnOpenFile.getModel().isPressed())  
        chooseFile.setDialogTitle("Open Test Project ");
        
        int openFile = chooseFile.showOpenDialog(null);
       if (openFile == JFileChooser.APPROVE_OPTION) {
            title.setText(chooseFile.getSelectedFile().getAbsolutePath() + " - " + "ZUI");
            dirPath.setText(chooseFile.getSelectedFile().getAbsolutePath());
            dirPath.setVisible(false);
            output.setText(chooseFile.getSelectedFile().getAbsolutePath() + "\nrun: \n");
           

        }
           

    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void btnRepAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepAllActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRepAllActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Sure? You want to Stop", "Confirm", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
        if (response == JOptionPane.OK_OPTION) {
            try {
                Runtime.getRuntime().exec("taskkill /f /im bash.exe");
                Runtime.getRuntime().exec("taskkill /f /im firefox.exe");
                Runtime.getRuntime().exec("taskkill /f /im cmd.exe");
                //Thread.sleep(1000);
                //this.dispose();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnOpenFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenFileMouseEntered
        // TODO add your handling code here:
        file.setBackground(Color.LIGHT_GRAY);
        btnOpenFile.setBackground(Color.LIGHT_GRAY);
        btnOpenFile.setToolTipText("Select Test Project");
    }//GEN-LAST:event_btnOpenFileMouseEntered

    private void btnOpenFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenFileMouseExited
        // TODO add your handling code here:
        file.setBackground(Color.getColor("#999999"));
        btnOpenFile.setBackground(Color.getColor("#999999"));
    }//GEN-LAST:event_btnOpenFileMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        // TODO add your handling code here:
        reportPanel.setBackground(Color.LIGHT_GRAY);
        btnReport.setBackground(Color.LIGHT_GRAY);
        btnReport.setToolTipText("View Report");
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        // TODO add your handling code here:
        reportPanel.setBackground(Color.getColor("#999999"));
        btnReport.setBackground(Color.getColor("#999999"));
    }//GEN-LAST:event_btnReportMouseExited

    private void btnResizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResizeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnResizeActionPerformed

    private void btnResizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResizeMouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState() != ZUI_app.MAXIMIZED_BOTH) {
            this.setExtendedState(ZUI_app.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(NORMAL);
        }

    }//GEN-LAST:event_btnResizeMouseClicked

    private void titleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - mouseX, evt.getYOnScreen() - mouseY);
    }//GEN-LAST:event_titleMouseDragged

    private void titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMousePressed
        // TODO add your handling code here:

        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_titleMousePressed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ZUI_app.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseEntered
        // TODO add your handling code here:
        playPanel.setBackground(Color.LIGHT_GRAY);
        btnPlay.setBackground(Color.LIGHT_GRAY);
        btnPlay.setToolTipText("Play TestCase");
    }//GEN-LAST:event_btnPlayMouseEntered

    private void btnPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseExited
        // TODO add your handling code here:
        playPanel.setBackground(Color.getColor("#999999"));
        btnPlay.setBackground(Color.getColor("#999999"));
    }//GEN-LAST:event_btnPlayMouseExited

    private void btnRepLastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepLastMouseEntered
        // TODO add your handling code here:
        repeatPanel.setBackground(Color.LIGHT_GRAY);
        btnRepLast.setBackground(Color.LIGHT_GRAY);
        btnRepLast.setToolTipText("Reapeate Last TestCase");
    }//GEN-LAST:event_btnRepLastMouseEntered

    private void btnRepLastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepLastMouseExited
        // TODO add your handling code here:
        repeatPanel.setBackground(Color.getColor("#999999"));
        btnRepLast.setBackground(Color.getColor("#999999"));
    }//GEN-LAST:event_btnRepLastMouseExited

    private void btnRepAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepAllMouseEntered
        // TODO add your handling code here:
        repAllPannel.setBackground(Color.LIGHT_GRAY);
        btnRepAll.setBackground(Color.LIGHT_GRAY);
        btnRepAll.setToolTipText("Reapeate All");
    }//GEN-LAST:event_btnRepAllMouseEntered

    private void btnRepAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepAllMouseExited
        // TODO add your handling code here:
        repAllPannel.setBackground(Color.getColor("#999999"));
        btnRepAll.setBackground(Color.getColor("#999999"));
    }//GEN-LAST:event_btnRepAllMouseExited

    private void btnContinueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseEntered
        // TODO add your handling code here:
        contPanel.setBackground(Color.LIGHT_GRAY);
        btnContinue.setBackground(Color.LIGHT_GRAY);
        btnContinue.setToolTipText("Skip & Continue the Test");
    }//GEN-LAST:event_btnContinueMouseEntered

    private void btnContinueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseExited
        // TODO add your handling code here:
        contPanel.setBackground(Color.getColor("#999999"));
        btnContinue.setBackground(Color.getColor("#999999"));
    }//GEN-LAST:event_btnContinueMouseExited

    private void btnStopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopMouseEntered
        // TODO add your handling code here:
        stopPanel.setBackground(Color.LIGHT_GRAY);
        btnStop.setBackground(Color.LIGHT_GRAY);
        btnStop.setToolTipText("Stop Testing");
    }//GEN-LAST:event_btnStopMouseEntered

    private void btnStopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopMouseExited
        // TODO add your handling code here:
        stopPanel.setBackground(Color.getColor("#999999"));
        btnStop.setBackground(Color.getColor("#999999"));
    }//GEN-LAST:event_btnStopMouseExited

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed

        // TODO add your handling code here:
        executeCMD();
              
//        try {
//            exec("cmd.exe","/c","start","E:/Training/iltTests/zeen/zeen.sh");
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        } 


    }//GEN-LAST:event_btnPlayActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        btnPlay.setEnabled(false);
//        btnContinue.setEnabled(false);
//        btnCreateProject.setEnabled(false);
//        btnRepAll.setEnabled(false);
//        btnStop.setEnabled(false);
//        btnRepLast.setEnabled(false);
//        btnReport.setEnabled(false);
//        btnCreateTC.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnCreateProjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateProjectMouseEntered
        // TODO add your handling code here:
        createProjectPanel.setBackground(Color.LIGHT_GRAY);
        btnCreateProject.setBackground(Color.LIGHT_GRAY);
        btnCreateProject.setToolTipText("Create New Project");
    }//GEN-LAST:event_btnCreateProjectMouseEntered

    private void btnCreateProjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateProjectMouseExited
        // TODO add your handling code here:
        createProjectPanel.setBackground(Color.getColor("#999999"));
        btnCreateProject.setBackground(Color.getColor("#999999"));
    }//GEN-LAST:event_btnCreateProjectMouseExited

    private void btnCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateProjectActionPerformed

    private void btnCreateTCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateTCMouseEntered
        // TODO add your handling code here:
        createTCPanel.setBackground(Color.LIGHT_GRAY);
        btnCreateTC.setBackground(Color.LIGHT_GRAY);
        btnCreateTC.setToolTipText("Create New Testcase");
    }//GEN-LAST:event_btnCreateTCMouseEntered

    private void btnCreateTCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateTCMouseExited
        // TODO add your handling code here:
        createTCPanel.setBackground(Color.getColor("#999999"));
        btnCreateTC.setBackground(Color.getColor("#999999"));
    }//GEN-LAST:event_btnCreateTCMouseExited

    private void btnCreateTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateTCActionPerformed

    private void createProjectPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createProjectPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_createProjectPanelMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZUI_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZUI_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZUI_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZUI_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZUI_app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnCreateProject;
    private javax.swing.JButton btnCreateTC;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRepAll;
    private javax.swing.JButton btnRepLast;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnResize;
    private javax.swing.JButton btnStop;
    private javax.swing.JPanel close;
    private javax.swing.JPanel contPanel;
    private javax.swing.JPanel createProjectPanel;
    private javax.swing.JPanel createTCPanel;
    private javax.swing.JLabel dirPath;
    private javax.swing.JPanel file;
    private javax.swing.JCheckBox headless;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollout;
    private javax.swing.JPanel minimize;
    private javax.swing.JPanel outPanel;
    private javax.swing.JTextArea output;
    private javax.swing.JPanel playPanel;
    private javax.swing.JPanel repAllPannel;
    private javax.swing.JPanel repeatPanel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JPanel restoreSize;
    private javax.swing.JPanel stopPanel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public void executeCMD() {
        SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                String[] command
                        = {
                            "cmd",};
                Process p;
                try {
                    p = Runtime.getRuntime().exec(command);
                    new Thread(new SyncPipe(p.getErrorStream(), System.err)).start();
                    new Thread(new SyncPipe(p.getInputStream(), System.out)).start();
                    PrintWriter stdin = new PrintWriter(p.getOutputStream());
                    stdin.write("c:\n");
                    stdin.write("bash.exe\n");
                    stdin.write("cd E:/Training/iltTests/zeen\n");
                    stdin.write("./zeen.sh\n");
                    stdin.println();
                    
                    stdin.close();
                    p.waitFor();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                
                return null;
                
            }
            
        };
        worker.execute();
        
    }
    
}
